spring:
  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3306/test01?useUnicode=true&characterEncoding=utf8
=======
    url: jdbc:mysql://localhost:3306/sqmx?useUnicode=true&characterEncoding=utf8
>>>>>>> refs/heads/xlb01
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

  mvc:
    view:
      prefix: /WEB-INF/JSP/
      suffix: .jsp
  thymeleaf:
    enabled: false
    cache: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      
mybatis:
  mapper-locations: com/tsinghuait/logistics/mapper/*.xml
  type-aliases-package: com.tsinghuait.logistics.pojo
#默认开启二级缓存
  configuration:
    cache-enabled: true 
  
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
    
    
fdfs:
  tracker-list: 192.168.25.142:22122
  pool: 
    jmx-enabled: false
    
  
   
    
  